### ISSUE TITLE
Migrate to AdoptOpenJdk api V3

### ISSUE THREAD

**Issue by nvuillam** [nvuillam/njre#15]
Ad discussed [here](https://github.com/AdoptOpenJDK/openjdk-api/issues/208) with AdoptOpenJdk maintainers, it is strongly encouraged to migrate to their V3 api, as the V2 has been marked as deprecated

It would be nice to migrate njre to V3 :)

https://api.adoptopenjdk.net/

**Comment by raftario** [comment]
I don't really plan on working on njre anymore as I don't have any use for it and it's not particularly depended on. I'll still look at PRs and I'm open to transfering ownership to another maintainer.

**Comment by nvuillam** [comment]
As my repos seems to be the ones the most using njre, it would make sense ... :)

https://github.com/raftario/njre/network/dependents?package_id=UGFja2FnZS00MDgxNjc1MDg%3D

I can own & maintain njre if you wish so !

**Comment by raftario** [comment]
Sounds good to me ! I'll transfer ownership.

**Comment by nvuillam** [comment]
Ok, I'll take good care of it :)

**Comment by nvuillam** [comment]
@raftario I may have some free time these next times, I'm ready for transfer when u are :)
My plans : 
- Migrate to AdoptOpenJdk V3 API
- Apply linters on project
- Put all doc directly in README

**Comment by raftario** [comment]
I already added you as a contributor on npm and initiated the GitHub repo transfer 👍

**Comment by nvuillam** [comment]
Didn't see the acceptance mail in the middle of all github notifs mails :)
Just accepted it, thanks !

**Comment by jhale1805** [comment]
@nvuillam What ended up being the status of this issue? I just tried to use `njre` for the first time and it seems like it can no longer download a JDK since the URLs it tries to pull the binaries from result in a server timeout...

**Comment by nvuillam** [comment]
@jhale1805 i've been lazy... while it worked i did nothing, are u sure V2 does not work anymore ?
If yes we have to upgrade to v3.... maybe u'd like to contribute ? :)

**Comment by jhale1805** [comment]
@nvuillam I tried both examples in the docs and each one gave a JSON parsing error that resulted from the response being the HTML of a server timeout page.

That said, while I've been programming for several years, I'm still new to JavaScript, so I could also totally believe that I did something wrong, even though I copy and pasted the exact code from the examples.

As for contributing, I'll definitely take a look. I'm currently a student so I don't know how much time I'll have. I also found an alternate way to accomplish my immediate goal, but this package does seem valuable to other projects I'd like to tackle in the future so I'll see what I can figure out.

**Comment by jhale1805** [comment]
Reading through their [migration guide](https://api.adoptopenjdk.net/migration.html), it looks like it might be as simple as changing the base url for the request...

**Comment by nvuillam** [comment]
That seems to be a great little student project, I'll write a note for your teachers, they'll surely appreciate that you already contribute to open source :)

**Comment by nvuillam** [comment]
I inherited njre maintenance after using it for https://github.com/nvuillam/node-java-caller ... which looks quite similar to node-java-connector ^^

**Comment by nvuillam** [comment]
@mheiges v1.0.0 has been released with your updates, and I also upgrade many dependencies :)

Thanks again for the PR !
